#!/usr/bin/env bash
# Launch an agent slot for iOS mobile app repos (git worktree by default).
# Every launch starts a FRESH session: any previous session for the slot is torn
# down (its branch is kept) and a new suffixed worktree is created from HEAD.
# Occupied slots always block: run ./.har/teardown.sh (or complete it) first, then relaunch.
#
# Usage: ./.har/launch.sh <agent-id> [--no-worktree]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=/dev/null
source "$SCRIPT_DIR/harness.env"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/agent-slot.sh"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/simulator.sh"

AGENT_ID="${1:-}"
USE_WORKTREE="${HARNESS_USE_WORKTREE:-true}"
WORK_UNIT_ID="${HAR_WORK_UNIT_ID:-}"
ATTEMPT_ID="${HAR_ATTEMPT_ID:-}"

for arg in "$@"; do
  case "$arg" in
    --no-worktree) USE_WORKTREE=false ;;
    --worktree) USE_WORKTREE=true ;;
    --work-id=*) WORK_UNIT_ID="${arg#*=}" ;;
    --attempt-id=*) ATTEMPT_ID="${arg#*=}" ;;
  esac
done

if [[ -n "$WORK_UNIT_ID" && -z "$ATTEMPT_ID" ]]; then
  ATTEMPT_ID="$(node -e 'process.stdout.write(require("crypto").randomUUID())')"
fi
export SLOT_WORK_UNIT_ID="$WORK_UNIT_ID"
export SLOT_ATTEMPT_ID="$ATTEMPT_ID"

if [[ -z "$AGENT_ID" ]]; then
  har_load_agent_slot_limits
  echo "Usage: $0 <agent-id> [--no-worktree]" >&2
  echo "  agent-id must be between ${HARNESS_AGENT_SLOT_MIN} and ${HARNESS_AGENT_SLOT_MAX}" >&2
  exit 1
fi

validate_agent_id "$AGENT_ID"

log() { echo "==> [agent-$AGENT_ID] $*" >&2; }

# Occupied slots always block a new launch — teardown/complete first, then relaunch.
if slot_is_occupied "$AGENT_ID"; then
  print_slot_occupied_warning "$AGENT_ID"
  echo "ERROR: slot ${AGENT_ID} is occupied." >&2
  echo "  Free it first: har env teardown ${AGENT_ID} (or complete ${AGENT_ID}), then har env launch ${AGENT_ID}." >&2
  exit 2
fi

"$SCRIPT_DIR/setup-infra.sh"

# Session worktree (default — use --no-worktree to work in repo root).
# Name encodes what the session is based on: <base-branch>-<sha4>-har-agent-<id>-<rand4>.
WORK_DIR="$REPO_ROOT"
WORKTREE_DIR=""
BRANCH=""
SUFFIX=""
BASE_BRANCH="$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "detached")"
BASE_COMMIT="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || true)"
if [ "$USE_WORKTREE" = true ]; then
  SHORT_SHA="$(git -C "$REPO_ROOT" rev-parse --short=4 HEAD)"
  SUFFIX="$(LC_ALL=C tr -dc 'a-z0-9' </dev/urandom 2>/dev/null | head -c 4 || true)"
  [ -n "$SUFFIX" ] || SUFFIX="$(printf '%04d' $(( RANDOM % 10000 )))"
  SESSION_NAME="${BASE_BRANCH//\//-}-${SHORT_SHA}-har-agent-${AGENT_ID}-${SUFFIX}"
  BRANCH="$SESSION_NAME"
  WORKTREE_DIR="$HOME/worktrees/${SESSION_NAME}"
  log "Creating session worktree at $WORKTREE_DIR (branch $BRANCH)..."
  git -C "$REPO_ROOT" worktree add "$WORKTREE_DIR" -b "$BRANCH"
  # Worktrees are always rooted at the git repo — if this project lives in a
  # subdirectory (monorepo), point WORK_DIR at the project inside the worktree.
  REL_PREFIX="$(git -C "$REPO_ROOT" rev-parse --show-prefix 2>/dev/null || true)"
  WORK_DIR="${WORKTREE_DIR%/}/${REL_PREFIX}"
  WORK_DIR="${WORK_DIR%/}"
else
  log "Using repo root (worktree disabled)"
fi

# Keep harness-generated files out of accidental `git add -A` commits in repos
# whose .gitignore doesn't know about har (applies to all worktrees too).
GIT_EXCLUDE="$(git -C "$REPO_ROOT" rev-parse --git-common-dir 2>/dev/null)/info/exclude"
if [ -n "$GIT_EXCLUDE" ] && [ -d "$(dirname "$GIT_EXCLUDE")" ]; then
  # .har/simulators covers harnesses scaffolded before it reached
  # gitignore.template, which only lands on init or maintain.
  for pattern in '.env.agent.*' 'ecosystem.agent.*.config.cjs' '.har/venv' '.har/simulators'; do
    grep -qxF "$pattern" "$GIT_EXCLUDE" 2>/dev/null || echo "$pattern" >> "$GIT_EXCLUDE"
  done
fi

ENV_FILE="$WORK_DIR/.env.agent.${AGENT_ID}"
log "Generating $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# Agent environment — generated by launch.sh
AGENT_ID=${AGENT_ID}
REPO_ROOT=${WORK_DIR}
WORKTREE_DIR=${WORKTREE_DIR}
NODE_ENV=test
EOF

REGISTRY_WRITTEN=false
mark_slot_failed() {
  local exit_code="$?"
  if [ "$exit_code" != "0" ] && [ "$REGISTRY_WRITTEN" = true ]; then
    log "Launch failed after creating the session. Recording failed slot state..."
    set +e
    har_sim_release "$AGENT_ID"
    SLOT_AGENT_ID="$AGENT_ID" \
    SLOT_MODE="$([ "$USE_WORKTREE" = true ] && echo worktree || echo root)" \
    SLOT_WORK_DIR="$WORK_DIR" \
    SLOT_SUFFIX="${SUFFIX:-}" \
    SLOT_WORKTREE_PATH="${WORKTREE_DIR:-}" \
    SLOT_BRANCH="${BRANCH:-}" \
    SLOT_BASE_BRANCH="${BASE_BRANCH:-}" \
    SLOT_BASE_COMMIT="${BASE_COMMIT:-}" \
    SLOT_STATUS="failed" \
    SLOT_LAST_ERROR="launch.sh exited with code ${exit_code}" \
      write_slot_registry
    log "  Work dir:  ${WORK_DIR}"
    log "  Env file:  ${ENV_FILE}"
    log "  Recovery:  fix the failure, then: har env teardown ${AGENT_ID} (or complete), then har env launch ${AGENT_ID}."
  fi
}
trap mark_slot_failed EXIT

# Record the session before slow or fragile setup so verify/status/teardown can
# recover partial launches that already created a worktree and env file.
SLOT_AGENT_ID="$AGENT_ID" \
SLOT_MODE="$([ "$USE_WORKTREE" = true ] && echo worktree || echo root)" \
SLOT_WORK_DIR="$WORK_DIR" \
SLOT_SUFFIX="${SUFFIX:-}" \
SLOT_WORKTREE_PATH="${WORKTREE_DIR:-}" \
SLOT_BRANCH="${BRANCH:-}" \
SLOT_BASE_BRANCH="${BASE_BRANCH:-}" \
SLOT_BASE_COMMIT="${BASE_COMMIT:-}" \
SLOT_STATUS="starting" \
  write_slot_registry
REGISTRY_WRITTEN=true

log "Provisioning toolchain (see harness.env: HARNESS_ECOSYSTEM, HARNESS_INSTALL_CMD)..."
HAR_WORK_DIR="$WORK_DIR" \
HAR_ENV_FILE="$ENV_FILE" \
HAR_WORKTREE_DIR="${WORKTREE_DIR:-}" \
HAR_REL_PREFIX="${REL_PREFIX:-}" \
HAR_AGENT_ID="$AGENT_ID" \
  "$SCRIPT_DIR/provision-toolchain.sh"

# Give this slot its own simulator. Written after provision-toolchain.sh so the
# per-slot device wins over the shared default when verify.sh sources the file.
if har_sim_per_slot_enabled; then
  log "Preparing this slot's simulator..."
  SIM_RESULT=""
  SIM_RESULT="$(har_sim_acquire "$AGENT_ID")" || {
    log "Could not prepare a simulator — see the messages above."
    exit 1
  }
  SIM_UDID="${SIM_RESULT%%$'\t'*}"
  SIM_NAME="${SIM_RESULT#*$'\t'}"
  # The device name goes under its own key: HARNESS_SIMULATOR_NAME means "model
  # to create" in harness.env, and overwriting it here would make its meaning
  # depend on which file was sourced last.
  {
    printf 'HARNESS_SIMULATOR_UDID=%q\n' "$SIM_UDID"
    printf 'HARNESS_SIMULATOR_DEVICE_NAME=%q\n' "$SIM_NAME"
    printf 'HARNESS_IOS_DESTINATION=%q\n' "platform=iOS Simulator,id=${SIM_UDID}"
  } >> "$ENV_FILE"
  log "Simulator: ${SIM_NAME} (${SIM_UDID})"
else
  log "Shared simulator mode (HARNESS_SIMULATOR_SHARED=true) — slots share ${HARNESS_SIMULATOR_NAME:-the configured device}."
fi

# Record the session in the slot registry — the source of truth for where
# this slot's code lives (status/verify/teardown resolve through it).
SLOT_AGENT_ID="$AGENT_ID" \
SLOT_MODE="$([ "$USE_WORKTREE" = true ] && echo worktree || echo root)" \
SLOT_WORK_DIR="$WORK_DIR" \
SLOT_SUFFIX="${SUFFIX:-}" \
SLOT_WORKTREE_PATH="${WORKTREE_DIR:-}" \
SLOT_BRANCH="${BRANCH:-}" \
SLOT_BASE_BRANCH="${BASE_BRANCH:-}" \
SLOT_BASE_COMMIT="${BASE_COMMIT:-}" \
SLOT_STATUS="active" \
  write_slot_registry

log "Agent $AGENT_ID is ready."
log ""
log "  WORK DIR (make ALL file edits under this path — never the main checkout):"
log "    ${WORK_DIR}"
if [ "$USE_WORKTREE" = true ]; then
  log "  Branch:    ${BRANCH} (based on ${BASE_BRANCH} @ ${BASE_COMMIT})"
fi
if [ -n "${SIM_NAME:-}" ]; then
  log "  Simulator: ${SIM_NAME} (${SIM_UDID})"
fi
log ""
log "  Verify:    ./.har/verify.sh $AGENT_ID"
log "  Teardown:  ./.har/teardown.sh $AGENT_ID   (keeps the branch)"
