import * as fs from 'fs';
import * as path from 'path';
import { readHarnessEnv } from '../harness/env';
import { getHarnessDir, readManifest, resolveHarnessRoot } from '../harness/manifest';
import { harnessUsesPm2 } from '../harness/capabilities';
import { runLaunchPreflight } from '../core/slot-preflight';
import { loadInfraState } from '../core/slot-ports';
import { writeSlotRegistry } from '../core/slot-registry';
import { defaultExec, ExecFn, LogFn, SleepFn, realSystemOps, SystemOps } from './exec';
import {
  cloneAgentDatabase,
  ensureMinioBucket,
  infraEnabled,
  infraPortDefault,
  HttpRequestFn,
} from './infra';
import {
  createSessionWorktree,
  GitRunner,
  resolveResumeSession,
  ResumedSession,
  seedGitExclude,
} from './worktree';
import { generateAgentEnvFile, appendSessionTelemetry } from './agent-env';
import { provisionToolchain, toolchainReady, quoteEnvValue } from './provision';
import {
  generateEcosystemConfig,
  startAgentProcesses,
  tmuxSessionName,
  waitForHealthCheck,
  HttpStatusFn,
} from './process';
import { pkgExec } from './node-pm';
import { acquireSimulator, perSlotEnabled, releaseSimulator } from './xcode-sim';
import { runSetupInfra } from './setup';

/** Pre-#236 capability detection: file/manifest presence, not a data manifest. */
export type ProcessManager = 'pm2' | 'simulator' | 'none';

export function detectProcessManager(repoPath: string): ProcessManager {
  if (harnessUsesPm2(repoPath)) return 'pm2';
  const harnessRoot = resolveHarnessRoot(repoPath);
  const manifest = readManifest(harnessRoot);
  if (manifest?.profile === 'ios') return 'simulator';
  if (fs.existsSync(path.join(getHarnessDir(harnessRoot), 'simulator.sh'))) return 'simulator';
  return 'none';
}

export interface LaunchSessionOptions {
  repoPath: string;
  agentId: number;
  worktree?: boolean;
  claude?: boolean;
  resume?: boolean;
  workUnitId?: string;
  attemptId?: string;
  /** Sink for the script-parity `==> [agent-N] …` progress lines (default stderr). */
  log?: LogFn;
  /** Sink for ERROR/WARN lines (default stderr). */
  error?: LogFn;
  // Injectable seams (tests)
  exec?: ExecFn;
  ops?: SystemOps;
  git?: GitRunner;
  homeDir?: string;
  suffix?: string;
  httpStatus?: HttpStatusFn;
  httpRequest?: HttpRequestFn;
  sleep?: SleepFn;
  portInUse?: (port: number) => boolean;
}

export interface LaunchSessionResult {
  code: number;
  workDir?: string;
  worktreePath?: string;
  branch?: string;
  ports?: Record<string, number>;
  previewUrls?: Record<string, string>;
}

const stderrLine: LogFn = (message) => process.stderr.write(`${message}\n`);

function heredocEnvFile(
  envFile: string,
  agentId: number,
  workDir: string,
  worktreeDir: string,
): void {
  // The template-less env file the cli/ios launch scripts write inline.
  const content = [
    '# Agent environment — generated by launch.sh',
    `AGENT_ID=${agentId}`,
    `REPO_ROOT=${workDir}`,
    `WORKTREE_DIR=${worktreeDir}`,
    'NODE_ENV=test',
    '',
  ].join('\n');
  fs.mkdirSync(path.dirname(envFile), { recursive: true });
  fs.writeFileSync(envFile, content);
}

/**
 * The package-side launch pipeline (#234) — the single implementation of what
 * the generated launch.sh scripts used to do, across all three profiles.
 * Ordering, registry writes, and key log lines match the retired bash.
 */
export async function launchSession(options: LaunchSessionOptions): Promise<LaunchSessionResult> {
  const repoRoot = resolveHarnessRoot(options.repoPath);
  const harnessDir = getHarnessDir(repoRoot);
  const env = readHarnessEnv(repoRoot);
  const agentId = options.agentId;
  const pm = detectProcessManager(repoRoot);
  const resume = options.resume ?? false;
  const useWorktree = options.worktree ?? (env.HARNESS_USE_WORKTREE ?? 'true') !== 'false';
  const projectName = env.HARNESS_PROJECT_NAME ?? '';
  const exec = options.exec ?? defaultExec;
  const ops = options.ops ?? realSystemOps;
  const errorLine = options.error ?? stderrLine;
  const log: LogFn = (message) =>
    (options.log ?? stderrLine)(`==> [agent-${agentId}] ${message}`);

  // ── Preflight (occupied slot, foreign PM2, port conflicts) ──────────────────
  const preflight = runLaunchPreflight({
    repoPath: repoRooted(options.repoPath, repoRoot),
    agentId,
    resume,
    worktree: useWorktree,
  });
  for (const note of preflight.notes) (options.log ?? stderrLine)(note);
  for (const warning of preflight.warnings) errorLine(`WARN: ${warning}`);
  if (preflight.exitCode !== 0) {
    for (const line of preflight.errors) errorLine(line);
    return { code: preflight.exitCode };
  }
  const appPorts = preflight.ports;
  if (pm === 'pm2' && appPorts) {
    log(`Ports: frontend=${appPorts.frontend} api=${appPorts.api} debug=${appPorts.debug}`);
  }

  // ── Shared infra (compose, template DB, simulator toolchain) ────────────────
  const setup = await runSetupInfra({
    repoPath: repoRoot,
    exec,
    log: options.log,
    sleep: options.sleep,
    portInUse: options.portInUse,
  });
  if (setup.code !== 0) return { code: setup.code };

  const infraState = loadInfraState(repoRoot, repoRoot);
  const dbPort = Number(infraState.AGENT_DB_PORT ?? infraPortDefault(env, 'db', 15432));
  const minioPort = Number(infraState.AGENT_MINIO_PORT ?? infraPortDefault(env, 'minio', 19000));
  const browserPort = Number(
    infraState.AGENT_BROWSER_PORT ?? infraPortDefault(env, 'browser', 13001),
  );

  if (pm === 'pm2') {
    if (infraEnabled(env, 'db') && env.HARNESS_TEMPLATE_DB) {
      cloneAgentDatabase(agentId, { env, dbPort, exec, log });
    }
    await ensureMinioBucket(agentId, minioPort, {
      env,
      log,
      httpRequest: options.httpRequest,
    });
  }

  // ── Session (fresh worktree, or resume state from the registry) ─────────────
  let session: ResumedSession;
  let relPrefix = '';
  if (resume) {
    const resolution = resolveResumeSession(repoRoot, agentId);
    if (!resolution.ok) {
      errorLine(`ERROR: ${resolution.message}`);
      return { code: resolution.code === 'not-resumable' ? 2 : 1 };
    }
    session = resolution.session;
    log(`Resuming session at ${session.workDir}`);
  } else {
    let workDir = repoRoot;
    let worktreeDir = '';
    let branch = '';
    let suffix = '';
    let baseBranch = 'detached';
    let baseCommit = '';
    if (useWorktree) {
      const created = createSessionWorktree({
        repoRoot,
        agentId,
        homeDir: options.homeDir,
        suffix: options.suffix,
        git: options.git,
      });
      log(`Creating session worktree at ${created.worktreeDir} (branch ${created.branch})...`);
      ({ workDir, worktreeDir, branch, suffix, baseBranch, baseCommit } = {
        workDir: created.workDir,
        worktreeDir: created.worktreeDir,
        branch: created.branch,
        suffix: created.suffix,
        baseBranch: created.baseBranch,
        baseCommit: created.baseCommit,
      });
      relPrefix = created.relPrefix;
    } else {
      log('Using repo root (worktree disabled)');
      const head = exec('git', ['-C', repoRoot, 'rev-parse', '--abbrev-ref', 'HEAD']);
      baseBranch = head.code === 0 ? head.stdout.trim() : 'detached';
      const sha = exec('git', ['-C', repoRoot, 'rev-parse', 'HEAD']);
      baseCommit = sha.code === 0 ? sha.stdout.trim() : '';
    }
    seedGitExclude(repoRoot, options.git);
    if (pm === 'simulator') seedExtraExcludePattern(repoRoot, '.har/simulators', exec);

    session = {
      workDir,
      worktreeDir,
      branch,
      suffix,
      baseBranch,
      baseCommit,
      useWorktree,
      envFile: path.join(workDir, `.env.agent.${agentId}`),
    };
  }

  // ── Agent env file ───────────────────────────────────────────────────────────
  log(`Generating ${session.envFile}...`);
  const rendered = generateAgentEnvFile({
    harnessDir,
    envFile: session.envFile,
    values: {
      agentId,
      apiPort: appPorts?.api ?? '',
      fePort: appPorts?.frontend ?? '',
      debugPort: appPorts?.debug ?? '',
      dbPort,
      minioPort,
      browserPort,
      repoRoot: session.workDir,
    },
  });
  if (!rendered) {
    heredocEnvFile(session.envFile, agentId, session.workDir, session.worktreeDir);
  }
  try {
    appendSessionTelemetry({
      agentId,
      repoPath: repoRoot,
      envFile: session.envFile,
      workDir: session.workDir,
      branch: session.branch || undefined,
      suffix: session.suffix || undefined,
      workUnitId: options.workUnitId,
      attemptId: options.attemptId,
    });
  } catch {
    // Telemetry attribution is best-effort, exactly as in the scripts.
  }

  const portsJson =
    pm === 'pm2' && appPorts
      ? { frontend: appPorts.frontend, api: appPorts.api, debug: appPorts.debug, db: dbPort }
      : undefined;
  const previewUrls =
    pm === 'pm2' && appPorts
      ? {
          frontend: `http://localhost:${appPorts.frontend}`,
          api: `http://localhost:${appPorts.api}`,
        }
      : undefined;

  const writeRegistry = (status: 'starting' | 'active' | 'failed', lastError?: string) =>
    writeSlotRegistry(repoRoot, {
      agentId,
      projectName,
      mode: session.useWorktree ? 'worktree' : 'root',
      workDir: session.workDir,
      suffix: session.suffix || undefined,
      worktreePath: session.worktreeDir || undefined,
      branch: session.branch || undefined,
      baseBranch: session.baseBranch || undefined,
      baseCommit: session.baseCommit || undefined,
      ports: portsJson,
      previewUrls,
      status,
      lastError,
      workUnitId: options.workUnitId,
      attemptId: options.attemptId,
    });

  writeRegistry('starting');

  // From here on, failures leave a resumable "failed" record (the bash EXIT trap).
  try {
    // ── Toolchain ──────────────────────────────────────────────────────────────
    if (resume && toolchainReady(session.workDir)) {
      log('Toolchain already provisioned — skipping install.');
    } else {
      log('Provisioning toolchain (see harness.env: HARNESS_ECOSYSTEM, HARNESS_INSTALL_CMD)...');
      await provisionToolchain({
        workDir: session.workDir,
        envFile: session.envFile,
        worktreeDir: session.worktreeDir || undefined,
        relPrefix,
        agentId,
        harnessEnv: env,
        ops,
      });
    }

    if (pm !== 'simulator' && env.HARNESS_DB_MINIMAL_BOOTSTRAP_CMD) {
      log('Running minimal data bootstrap...');
      const bootstrap = exec('bash', [
        '-c',
        `cd ${JSON.stringify(session.workDir)} && set -a && . ${JSON.stringify(session.envFile)} && set +a && eval "$HARNESS_DB_MINIMAL_BOOTSTRAP_CMD"`,
      ], { env: { ...process.env, ...env } });
      if (bootstrap.code !== 0) throw new Error(`minimal data bootstrap failed (${bootstrap.code})`);
    }

    // ── Per-profile app runtime ────────────────────────────────────────────────
    let simName = '';
    let simUdid = '';
    if (pm === 'pm2' && appPorts) {
      const ecosystemFile = generateEcosystemConfig({
        workDir: session.workDir,
        agentId,
        projectName,
        fePort: appPorts.frontend,
        debugPort: appPorts.debug,
        templatePath: path.join(harnessDir, 'ecosystem.agent.template.cjs'),
      });
      log(`Generating ${ecosystemFile}...`);
      log('Starting PM2 processes...');
      startAgentProcesses({
        projectName,
        agentId,
        pkgExecPrefix: pkgExec(undefined, env, ops).split(' '),
        exec,
        workDir: session.workDir,
        ecosystemFile,
      });
      await waitForHealthCheck({
        apiPort: appPorts.api,
        healthCheckPath: env.HARNESS_HEALTH_CHECK_PATH,
        agentId,
        log,
        httpStatus: options.httpStatus,
        sleep: options.sleep,
      });
    } else if (pm === 'simulator') {
      if (perSlotEnabled(env)) {
        log("Preparing this slot's simulator...");
        const sim = await acquireSimulator({
          env,
          harnessDir,
          repoRoot,
          agentId,
        });
        if (!sim) {
          log('Could not prepare a simulator — see the messages above.');
          throw new Error('simulator acquisition failed');
        }
        ({ udid: simUdid, name: simName } = sim);
        fs.appendFileSync(
          session.envFile,
          [
            `HARNESS_SIMULATOR_UDID=${quoteEnvValue(simUdid)}`,
            `HARNESS_SIMULATOR_DEVICE_NAME=${quoteEnvValue(simName)}`,
            `HARNESS_IOS_DESTINATION=${quoteEnvValue(`platform=iOS Simulator,id=${simUdid}`)}`,
            '',
          ].join('\n'),
        );
        log(`Simulator: ${simName} (${simUdid})`);
      } else {
        log(
          `Shared simulator mode (HARNESS_SIMULATOR_SHARED=true) — slots share ${env.HARNESS_SIMULATOR_NAME ?? 'the configured device'}.`,
        );
      }
    }

    writeRegistry('active');

    if (options.claude && pm === 'pm2') {
      const tmux = tmuxSessionName(projectName, agentId);
      if (exec('tmux', ['has-session', '-t', tmux]).code === 0) {
        exec('tmux', ['kill-session', '-t', tmux]);
      }
      exec('tmux', [
        'new-session', '-d', '-s', tmux, '-c', session.workDir,
        `set -a; [ -f '${session.envFile}' ] && . '${session.envFile}'; set +a; exec claude`,
      ]);
      log(`Claude session: tmux attach -t ${tmux}`);
    }

    // ── Summary (script-parity closing block) ─────────────────────────────────
    if (pm === 'pm2') (options.log ?? stderrLine)('');
    log(pm === 'pm2' ? `Agent ${agentId} is ready!` : `Agent ${agentId} is ready.`);
    log('');
    log('  WORK DIR (make ALL file edits under this path — never the main checkout):');
    log(`    ${session.workDir}`);
    if (session.useWorktree) {
      log(`  Branch:    ${session.branch} (based on ${session.baseBranch} @ ${session.baseCommit})`);
    }
    if (pm === 'pm2' && appPorts) {
      log(`  Frontend:  http://localhost:${appPorts.frontend}`);
      log(`  API:       http://localhost:${appPorts.api}`);
      if (infraEnabled(env, 'db')) log(`  Database:  agent_${agentId} @ localhost:${dbPort}`);
    }
    if (simName) log(`  Simulator: ${simName} (${simUdid})`);
    log('');
    if (pm === 'pm2') {
      log('  Edits under the work dir hot-reload in the running slot;');
      log(`  use har env agent ${agentId} restart if a change doesn't take.`);
    }
    log(`  Verify:    ./.har/verify.sh ${agentId}`);
    log(`  Teardown:  ./.har/teardown.sh ${agentId}   (keeps the branch)`);

    return {
      code: 0,
      workDir: session.workDir,
      worktreePath: session.worktreeDir || undefined,
      branch: session.branch || undefined,
      ports: portsJson,
      previewUrls,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    log(
      resume
        ? 'Resume failed. Recording failed slot state...'
        : 'Launch failed after creating the session. Recording failed slot state...',
    );
    if (pm === 'simulator') {
      try {
        releaseSimulator({ env, harnessDir, repoRoot, agentId });
      } catch {
        /* release is best-effort in the failure path */
      }
    }
    try {
      writeRegistry('failed', `launch exited with error: ${message}`);
    } catch {
      /* the failure record must not mask the launch error */
    }
    log(`  Work dir:  ${session.workDir}`);
    log(`  Env file:  ${session.envFile}`);
    log(`  Recovery:  har env launch ${agentId} --resume  # or ./.har/launch.sh ${agentId} --resume`);
    errorLine(`ERROR: ${message}`);
    return { code: 1 };
  }
}

/** Extra exclude line the ios launch script seeds beyond the shared patterns. */
function seedExtraExcludePattern(repoRoot: string, pattern: string, exec: ExecFn): void {
  const commonDir = exec('git', ['-C', repoRoot, 'rev-parse', '--git-common-dir']);
  if (commonDir.code !== 0) return;
  const resolved = path.isAbsolute(commonDir.stdout.trim())
    ? commonDir.stdout.trim()
    : path.resolve(repoRoot, commonDir.stdout.trim());
  const excludeFile = path.join(resolved, 'info', 'exclude');
  if (!fs.existsSync(path.dirname(excludeFile))) return;
  const existing = fs.existsSync(excludeFile) ? fs.readFileSync(excludeFile, 'utf8') : '';
  if (existing.split('\n').includes(pattern)) return;
  fs.appendFileSync(excludeFile, `${pattern}\n`);
}

/** repoPath for preflight: preserve the caller's path when it maps to the same root. */
function repoRooted(requested: string, resolved: string): string {
  return path.resolve(requested) === resolved ? requested : resolved;
}
