import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as readline from 'readline';
import { writeFileSafe } from '../utils/file-ops';
import { info, warn } from '../utils/logging';
import { resolveTemplatesDir } from '../utils/paths';
import { computeFileChecksum, readManifest, writeManifest } from './manifest';
import { AgentSkillTarget, ScaffoldedAgentFile } from './schema';

export const AGENT_SKILL_TARGETS: AgentSkillTarget[] = ['claude', 'cursor', 'codex'];

export const MANAGED_HEADER =
  '<!-- managed by har — regenerated by `har agents install` / `har env maintain`; edit at your own risk -->';

interface SkillManifestEntry {
  id: string;
  body: string;
  title: string;
  claude?: { frontmatter: Record<string, string | boolean | number> };
  cursor?: { command: boolean };
  codex?: { promptName: string };
}

interface SkillsManifest {
  version: number;
  skills: SkillManifestEntry[];
}

interface RenderedSkillFile {
  agent: AgentSkillTarget;
  skill: string;
  scope: 'repo' | 'global';
  /** Repo-relative for scope 'repo'; '~/…' for scope 'global'. */
  relPath: string;
  content: string;
}

function agentSkillsTemplateDir(): string {
  const dir = path.join(resolveTemplatesDir(), 'agent-skills');
  if (!fs.existsSync(dir)) {
    throw new Error('Agent skills templates not found (templates/agent-skills). Run npm run build.');
  }
  return dir;
}

function readSkillsManifest(): SkillsManifest {
  const manifestPath = path.join(agentSkillsTemplateDir(), 'skills.manifest.json');
  return JSON.parse(fs.readFileSync(manifestPath, 'utf8')) as SkillsManifest;
}

function readSkillBody(entry: SkillManifestEntry): string {
  return fs.readFileSync(path.join(agentSkillsTemplateDir(), entry.body), 'utf8');
}

function renderYamlValue(value: string | boolean | number): string {
  if (typeof value === 'string') return JSON.stringify(value);
  return String(value);
}

function renderClaudeSkill(entry: SkillManifestEntry, body: string): string {
  const frontmatter = entry.claude?.frontmatter ?? { name: entry.id, description: entry.title };
  const lines = Object.entries(frontmatter).map(([key, value]) => `${key}: ${renderYamlValue(value)}`);
  return `---\n${lines.join('\n')}\n---\n\n${MANAGED_HEADER}\n\n${body}`;
}

function renderPlainSkill(body: string): string {
  return `${MANAGED_HEADER}\n\n${body}`;
}

export function renderSkillFiles(agents: AgentSkillTarget[]): RenderedSkillFile[] {
  const manifest = readSkillsManifest();
  const files: RenderedSkillFile[] = [];

  for (const entry of manifest.skills) {
    const body = readSkillBody(entry);
    if (agents.includes('claude')) {
      files.push({
        agent: 'claude',
        skill: entry.id,
        scope: 'repo',
        relPath: path.join('.claude', 'skills', entry.id, 'SKILL.md'),
        content: renderClaudeSkill(entry, body),
      });
    }
    if (agents.includes('cursor') && entry.cursor?.command) {
      files.push({
        agent: 'cursor',
        skill: entry.id,
        scope: 'repo',
        relPath: path.join('.cursor', 'commands', `${entry.id}.md`),
        content: renderPlainSkill(body),
      });
    }
    if (agents.includes('codex') && entry.codex?.promptName) {
      files.push({
        agent: 'codex',
        skill: entry.id,
        scope: 'global',
        relPath: path.posix.join('~', '.codex', 'prompts', `${entry.codex.promptName}.md`),
        content: renderPlainSkill(body),
      });
    }
  }
  return files;
}

export function resolveScaffoldPath(repoPath: string, file: Pick<RenderedSkillFile, 'scope' | 'relPath'>): string {
  if (file.scope === 'global') {
    return path.join(os.homedir(), file.relPath.replace(/^~\//, ''));
  }
  return path.join(repoPath, file.relPath);
}

function isHarManaged(filePath: string): boolean {
  return fs.readFileSync(filePath, 'utf8').includes(MANAGED_HEADER);
}

export interface ScaffoldAgentSkillsResult {
  written: string[];
  skipped: string[];
}

export function scaffoldAgentSkills(
  repoPath: string,
  agents: AgentSkillTarget[],
  options: { force?: boolean } = {},
): ScaffoldAgentSkillsResult {
  const written: string[] = [];
  const skipped: string[] = [];
  const records: ScaffoldedAgentFile[] = [];

  for (const file of renderSkillFiles(agents)) {
    const destPath = resolveScaffoldPath(repoPath, file);
    if (fs.existsSync(destPath) && !options.force && !isHarManaged(destPath)) {
      warn(`Skipped ${file.relPath} — exists with user modifications (use --force to overwrite)`);
      skipped.push(file.relPath);
      continue;
    }
    writeFileSafe(destPath, file.content);
    written.push(file.relPath);
    records.push({
      path: file.relPath,
      agent: file.agent,
      skill: file.skill,
      checksum: computeFileChecksum(file.content),
      scope: file.scope,
    });
  }

  recordScaffoldedFiles(repoPath, agents, records);
  return { written, skipped };
}

/** Merge freshly scaffolded records into .har/manifest.json (no-op when no harness manifest exists yet). */
function recordScaffoldedFiles(
  repoPath: string,
  agents: AgentSkillTarget[],
  records: ScaffoldedAgentFile[],
): void {
  const manifest = readManifest(repoPath);
  if (!manifest) return;

  const kept = (manifest.scaffoldedAgentFiles ?? []).filter(
    (entry) => !agents.includes(entry.agent),
  );
  writeManifest(repoPath, {
    ...manifest,
    scaffoldedAgentFiles: [...kept, ...records],
    updatedAt: new Date().toISOString(),
  });
}

export function removeAgentSkills(repoPath: string, agents: AgentSkillTarget[]): string[] {
  const removed: string[] = [];
  for (const file of renderSkillFiles(agents)) {
    const destPath = resolveScaffoldPath(repoPath, file);
    if (!fs.existsSync(destPath)) continue;
    if (!isHarManaged(destPath)) {
      warn(`Kept ${file.relPath} — has user modifications`);
      continue;
    }
    fs.rmSync(destPath);
    removed.push(file.relPath);
    const parent = path.dirname(destPath);
    if (fs.existsSync(parent) && fs.readdirSync(parent).length === 0) {
      fs.rmdirSync(parent);
    }
  }

  const manifest = readManifest(repoPath);
  if (manifest?.scaffoldedAgentFiles) {
    writeManifest(repoPath, {
      ...manifest,
      scaffoldedAgentFiles: manifest.scaffoldedAgentFiles.filter(
        (entry) => !agents.includes(entry.agent),
      ),
      updatedAt: new Date().toISOString(),
    });
  }
  return removed;
}

/** Agents already scaffolded (per manifest) or plausibly in use (config dir present). */
export function detectAgentTargets(repoPath: string): AgentSkillTarget[] {
  const manifest = readManifest(repoPath);
  const scaffolded = new Set((manifest?.scaffoldedAgentFiles ?? []).map((entry) => entry.agent));
  const detected = new Set<AgentSkillTarget>(scaffolded);

  if (fs.existsSync(path.join(repoPath, '.claude'))) detected.add('claude');
  if (fs.existsSync(path.join(repoPath, '.cursor'))) detected.add('cursor');
  if (fs.existsSync(path.join(os.homedir(), '.codex'))) detected.add('codex');
  return AGENT_SKILL_TARGETS.filter((agent) => detected.has(agent));
}

export function parseAgentTargets(raw: string): AgentSkillTarget[] {
  if (typeof raw !== 'string' || !raw.trim()) {
    return [];
  }
  const parts = raw
    .split(',')
    .map((part) => part.trim().toLowerCase())
    .filter(Boolean);
  const invalid = parts.filter((part) => !(AGENT_SKILL_TARGETS as string[]).includes(part));
  if (invalid.length > 0) {
    throw new Error(
      `Unknown agent target(s): ${invalid.join(', ')}. Valid: ${AGENT_SKILL_TARGETS.join(', ')}`,
    );
  }
  return AGENT_SKILL_TARGETS.filter((agent) => parts.includes(agent));
}

export interface AgentSkillsScaffoldOptions {
  repoPath: string;
  /** Comma-separated agent list from --agents; undefined = auto-detect / prompt. */
  agents?: string;
  /** false = --no-agents: skip entirely. */
  enabled?: boolean;
  autoYes?: boolean;
  force?: boolean;
  mode: 'init' | 'maintain';
}

export async function handleAgentSkills(options: AgentSkillsScaffoldOptions): Promise<boolean> {
  const { repoPath, mode } = options;

  if (options.enabled === false) return false;

  let targets: AgentSkillTarget[];
  // yargs can set `agents: false` when `--no-agents` is also a flag name collision
  if (typeof options.agents === 'string') {
    targets = parseAgentTargets(options.agents);
  } else if (options.agents !== undefined) {
    return false;
  } else {
    targets = detectAgentTargets(repoPath);
    if (targets.length === 0) return false;

    const manifest = readManifest(repoPath);
    const alreadyScaffolded = (manifest?.scaffoldedAgentFiles ?? []).length > 0;
    const shouldPrompt = !options.autoYes && !(mode === 'maintain' && alreadyScaffolded);
    if (shouldPrompt) {
      const accepted = await askYesNo(
        `Scaffold agent skills (/setup-har, /har-wt, /har-maintain) for: ${targets.join(', ')}? [Y/n]`,
      );
      if (!accepted) {
        info('Skipped agent skills');
        return false;
      }
    }
  }

  if (targets.length === 0) return false;

  const result = scaffoldAgentSkills(repoPath, targets, { force: options.force });
  for (const file of result.written) {
    info(`${mode === 'maintain' ? 'Refreshed' : 'Wrote'} ${file}`);
  }
  return result.written.length > 0;
}

async function askYesNo(question: string): Promise<boolean> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stderr });
  return new Promise((resolve) => {
    process.stderr.write(`${question} `);
    rl.once('line', (answer) => {
      rl.close();
      const trimmed = answer.trim();
      if (trimmed === '') {
        resolve(true);
        return;
      }
      resolve(/^y(es)?$/i.test(trimmed));
    });
  });
}
