import * as fs from 'fs';
import * as path from 'path';

/** Generated by launch.sh at the work dir root — must not be committed. */
export const HARNESS_ROOT_GITIGNORE_PATTERNS = [
  '.env.agent.*',
  'ecosystem.agent.*.config.cjs',
] as const;

/**
 * Append harness-generated root artifacts to the checkout's `.gitignore`
 * when missing (repos scaffolded before this feature existed).
 */
export function ensureRootGitignorePatterns(checkoutDir: string): void {
  const gitignorePath = path.join(checkoutDir, '.gitignore');
  const content = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf8') : '';
  const lines = content.split('\n').map((line) => line.trim());
  const missing = HARNESS_ROOT_GITIGNORE_PATTERNS.filter((pattern) => !lines.includes(pattern));
  if (missing.length === 0) return;

  const header =
    lines.length === 0 || content.trim().length === 0
      ? '# HAR agent slot artifacts (generated by .har/launch.sh)\n'
      : '';
  const suffix = content.length === 0 || content.endsWith('\n') ? '' : '\n';
  const block =
    lines.some((line) => line.includes('HAR agent slot artifacts')) || header.length === 0
      ? `${missing.join('\n')}\n`
      : `${header}${missing.join('\n')}\n`;

  fs.writeFileSync(gitignorePath, `${content}${suffix}${block}`);
}
