#!/usr/bin/env bash
# Launch an agent slot for CLI/library repos (git worktree by default, optional Docker infra).
#
# Usage: ./.har/launch.sh <agent-id> [--no-worktree]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=/dev/null
source "$SCRIPT_DIR/harness.env"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/agent-slot.sh"

AGENT_ID="${1:-}"
USE_WORKTREE="${HARNESS_USE_WORKTREE:-true}"

for arg in "$@"; do
  case "$arg" in
    --no-worktree) USE_WORKTREE=false ;;
    --worktree) USE_WORKTREE=true ;;
  esac
done

if [[ -z "$AGENT_ID" ]]; then
  echo "Usage: $0 <agent-id> [--no-worktree]" >&2
  echo "  agent-id must be between ${HARNESS_AGENT_SLOT_MIN} and ${HARNESS_AGENT_SLOT_MAX}" >&2
  exit 1
fi

validate_agent_id "$AGENT_ID"

log() { echo "==> [agent-$AGENT_ID] $*" >&2; }

"$SCRIPT_DIR/setup-infra.sh"

WORK_DIR="$REPO_ROOT"
WORKTREE_DIR="$HOME/worktrees/${HARNESS_PROJECT_NAME}-agent-${AGENT_ID}"

if [ "$USE_WORKTREE" = true ]; then
  if [ -d "$WORKTREE_DIR" ]; then
    log "Worktree already exists at $WORKTREE_DIR"
  else
    log "Creating git worktree at $WORKTREE_DIR..."
    git -C "$REPO_ROOT" worktree add "$WORKTREE_DIR" -b "har-agent-${AGENT_ID}" 2>/dev/null || \
      git -C "$REPO_ROOT" worktree add "$WORKTREE_DIR" HEAD
  fi
  # Worktrees are always rooted at the git repo — if this project lives in a
  # subdirectory (monorepo), point WORK_DIR at the project inside the worktree.
  REL_PREFIX="$(git -C "$REPO_ROOT" rev-parse --show-prefix 2>/dev/null || true)"
  WORK_DIR="${WORKTREE_DIR%/}/${REL_PREFIX}"
  WORK_DIR="${WORK_DIR%/}"
else
  log "Using repo root (worktree disabled)"
fi

ENV_FILE="$WORK_DIR/.env.agent.${AGENT_ID}"
log "Generating $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# Agent environment — generated by launch.sh
AGENT_ID=${AGENT_ID}
REPO_ROOT=${WORK_DIR}
WORKTREE_DIR=${WORKTREE_DIR}
NODE_ENV=test
EOF

if [ -f "$WORK_DIR/package.json" ]; then
  log "Installing dependencies..."
  (cd "$WORK_DIR" && npm install --silent)
elif [ -f "$WORK_DIR/go.mod" ]; then
  log "Go module detected in work dir (run go mod download if needed)"
fi

# Monorepo: file:/workspace deps may resolve modules from the repo root — install there too
if [ -n "${REL_PREFIX:-}" ] && [ -f "$WORKTREE_DIR/package.json" ] && [ ! -d "$WORKTREE_DIR/node_modules" ]; then
  log "Installing monorepo root dependencies in $WORKTREE_DIR..."
  (cd "$WORKTREE_DIR" && npm install --silent)
fi

log "Agent $AGENT_ID is ready."
log "  Work dir:  $WORK_DIR"
[ "$USE_WORKTREE" = true ] && log "  Worktree:  $WORKTREE_DIR"
log "  Verify:    ./.har/verify.sh $AGENT_ID"
log "  Teardown:  ./.har/teardown.sh $AGENT_ID"
