#!/usr/bin/env bash
# Launch an agent slot for CLI/library repos (no Docker/PM2).
#
# Usage: ./.har/launch.sh <agent-id> [--worktree]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=/dev/null
source "$SCRIPT_DIR/harness.env"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/agent-slot.sh"

AGENT_ID="${1:-}"
USE_WORKTREE=false

for arg in "$@"; do
  case "$arg" in
    --worktree) USE_WORKTREE=true ;;
  esac
done

if [[ -z "$AGENT_ID" ]]; then
  echo "Usage: $0 <agent-id> [--worktree]" >&2
  echo "  agent-id must be between ${HARNESS_AGENT_SLOT_MIN} and ${HARNESS_AGENT_SLOT_MAX}" >&2
  exit 1
fi

validate_agent_id "$AGENT_ID"

log() { echo "==> [agent-$AGENT_ID] $*" >&2; }

"$SCRIPT_DIR/setup-infra.sh"

WORK_DIR="$REPO_ROOT"
if [ "$USE_WORKTREE" = true ]; then
  WORKTREE_DIR="$HOME/worktrees/${HARNESS_PROJECT_NAME}-agent-${AGENT_ID}"
  if [ -d "$WORKTREE_DIR" ]; then
    log "Worktree already exists at $WORKTREE_DIR"
  else
    log "Creating git worktree at $WORKTREE_DIR..."
    git -C "$REPO_ROOT" worktree add "$WORKTREE_DIR" -b "agent-${AGENT_ID}" 2>/dev/null || \
      git -C "$REPO_ROOT" worktree add "$WORKTREE_DIR" HEAD
  fi
  WORK_DIR="$WORKTREE_DIR"
fi

ENV_FILE="$REPO_ROOT/.env.agent.${AGENT_ID}"
log "Generating $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# Agent environment — generated by launch.sh
AGENT_ID=${AGENT_ID}
REPO_ROOT=${WORK_DIR}
NODE_ENV=test
EOF

if [ -f "$WORK_DIR/package.json" ]; then
  log "Installing dependencies..."
  (cd "$WORK_DIR" && npm install --silent)
fi

log "Agent $AGENT_ID is ready."
log "  Work dir:  $WORK_DIR"
log "  Verify:    ./.har/verify.sh $AGENT_ID"
log "  Teardown:  ./.har/teardown.sh $AGENT_ID"
