#!/usr/bin/env bash
# Launch an agent slot for @har/cli development.
#
# Usage: ./.har/launch.sh <agent-id> [--no-worktree]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=/dev/null
source "$SCRIPT_DIR/harness.env"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/agent-slot.sh"

AGENT_ID="${1:-}"
USE_WORKTREE="${HARNESS_USE_WORKTREE:-true}"

for arg in "$@"; do
  case "$arg" in
    --no-worktree) USE_WORKTREE=false ;;
    --worktree) USE_WORKTREE=true ;;
  esac
done

if [[ -z "$AGENT_ID" ]]; then
  echo "Usage: $0 <agent-id> [--no-worktree]" >&2
  echo "  agent-id must be between ${HARNESS_AGENT_SLOT_MIN} and ${HARNESS_AGENT_SLOT_MAX}" >&2
  exit 1
fi

validate_agent_id "$AGENT_ID"

log() { echo "==> [agent-$AGENT_ID] $*" >&2; }

"$SCRIPT_DIR/setup-infra.sh"

WORK_DIR="$REPO_ROOT"
WORKTREE_DIR="$HOME/worktrees/${HARNESS_PROJECT_NAME}-agent-${AGENT_ID}"

if [ "$USE_WORKTREE" = true ]; then
  if [ -d "$WORKTREE_DIR" ]; then
    log "Worktree already exists at $WORKTREE_DIR"
  else
    log "Creating git worktree at $WORKTREE_DIR..."
    git -C "$REPO_ROOT" worktree add "$WORKTREE_DIR" -b "har-agent-${AGENT_ID}" 2>/dev/null || \
      git -C "$REPO_ROOT" worktree add "$WORKTREE_DIR" HEAD
  fi
  WORK_DIR="$WORKTREE_DIR"
else
  log "Using repo root (worktree disabled)"
fi

ENV_FILE="$WORK_DIR/.env.agent.${AGENT_ID}"
log "Generating $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# Agent environment — generated by launch.sh
AGENT_ID=${AGENT_ID}
REPO_ROOT=${WORK_DIR}
WORKTREE_DIR=${WORKTREE_DIR}
NODE_ENV=test
EOF

log "Installing dependencies..."
(cd "$WORK_DIR" && npm install --silent)

log "Agent $AGENT_ID is ready."
log "  Work dir:  $WORK_DIR"
[ "$USE_WORKTREE" = true ] && log "  Worktree:  $WORKTREE_DIR"
log "  Verify:    ./.har/verify.sh $AGENT_ID"
log "  Teardown:  ./.har/teardown.sh $AGENT_ID"
